### ISSUE TITLE
Typescript sync-mode compilation issue

### ISSUE THREAD

**Issue by lkipke** [olivierwilkinson/webdriverio-testing-library#2]
# Summary

First, thank you for making these bindings, this is great!

I have a webdriver project written in Typescript, that uses webdriverio's sync mode (it leverages the global type definitions for the `WebdriverIO` namespace that are defined in `@wdio/sync`). When I try to import this project, all of the async global types from `webdriverio` are getting pulled in as well. This causes compilation issues because now TS thinks that the browser APIs should be returning promises.

# Possible cause

I believe it might be caused by pulling in the base `webdriverio` package, which defines the global async type definitions:
https://github.com/testing-library/webdriverio-testing-library/blob/539a4e200d93e98d97a6bb45ee268924bbcc0e99/src/index.ts#L6

Also, I took a look at the tests in this repo and it seems like this might be a known issue:
https://github.com/testing-library/webdriverio-testing-library/blob/539a4e200d93e98d97a6bb45ee268924bbcc0e99/test/sync.e2e.js#L1-L4

**Comment by olivierwilkinson** [comment]
Hi there, thanks for raising this!

You are absolutely right that importing the `webdriverio` package directly is defining the global namespace with the async type definitions and breaking compilation when using sync mode.

It wasn't a known issue unfortunately, the sync tests were in a js file because of difficulties getting Typescript to ignore the previous declaration of the command types in `test/setupBrowser.e2e.ts`. 

I haven't been able to find a simple solution to this, it seems that the way things are setup right now the project needs to build with either the async types or the sync types bundled which is a bit problematic. I'm going to keep looking into this during the week though so I will update you with my progress 😄.

**Comment by lkipke** [comment]
Thanks @olivierwilkinson! 😄

**Comment by olivierwilkinson** [comment]
@lkipke I have raised a PR which I think fixes the problem 😁 

I've released to the `next` channel so you'll be able to test the new version out by installing `@testing-library/webdriverio@next`. Let me know if it's working well for you, it would be great to catch any other issues early!

**Comment by lkipke** [comment]
@olivierwilkinson Thank you for the quick turnaround! I pulled in the `@next` version and it compiled and ran successfully 🎉

**Comment by olivierwilkinson** [comment]
Great! 😄 I've merged into master so you can install via the main distribution channel now: `@testing-library/webdriverio@^2.0.0`

No problem on the turnaround, thanks again for flagging this!
